"""Shared statistical and LaTeX helpers for the Chapter 8 tables.

The experimental unit is always one repeated run.  Group comparisons are
therefore paired by run before their mean difference, standard error, and
two-sided Wilcoxon signed-rank p-value are computed.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
import pandas as pd
from scipy.stats import wilcoxon


@dataclass(frozen=True)
class PairedSummary:
    """Summary of a paired comparison, expressed in percentage points."""

    mean_a_pct: float
    mean_b_pct: float
    diff_pp: float
    sem_diff_pp: float
    p_value: float
    n_pairs: int

    def audit_dict(self) -> dict[str, float | int]:
        return asdict(self)


def require_columns(data: pd.DataFrame, required: Iterable[str], source: Path) -> None:
    """Fail with a useful error if an input artifact has changed schema."""

    missing = set(required) - set(data.columns)
    if missing:
        raise ValueError(f"{source} is missing columns: {sorted(missing)}")


def paired_columns_summary(
    data: pd.DataFrame,
    *,
    run_col: str,
    a_col: str,
    b_col: str,
) -> PairedSummary:
    """Summarise two rate columns after enforcing one observation per run."""

    pairs = data[[run_col, a_col, b_col]].dropna().sort_values(run_col)
    if pairs[run_col].duplicated().any():
        raise ValueError(f"Duplicate {run_col!r} values in paired comparison")
    if len(pairs) < 2:
        raise ValueError("A paired comparison requires at least two complete runs")

    a = pairs[a_col].astype(float)
    b = pairs[b_col].astype(float)
    # The inputs are discrete event counts divided by fixed group sizes.  Round
    # before ranking absolute differences so floating-point noise cannot split
    # mathematically tied Wilcoxon ranks (recommended by scipy.stats.wilcoxon).
    diff_pp = ((a - b) * 100.0).round(12)
    if np.allclose(diff_pp, 0.0):
        p_value = 1.0
    else:
        p_value = float(wilcoxon(diff_pp, alternative="two-sided").pvalue)

    return PairedSummary(
        mean_a_pct=float(a.mean() * 100.0),
        mean_b_pct=float(b.mean() * 100.0),
        diff_pp=float(diff_pp.mean()),
        sem_diff_pp=float(diff_pp.sem(ddof=1)),
        p_value=p_value,
        n_pairs=len(pairs),
    )


def paired_groups_summary(
    data: pd.DataFrame,
    *,
    run_col: str,
    group_col: str,
    value_col: str,
    group_a: str,
    group_b: str,
) -> PairedSummary:
    """Pivot two named groups by run and pass them to ``paired_columns_summary``."""

    counts = data.groupby([run_col, group_col], observed=True).size()
    if (counts != 1).any():
        raise ValueError("Expected exactly one row per run and comparison group")

    wide = data.pivot(index=run_col, columns=group_col, values=value_col)
    missing_groups = {group_a, group_b} - set(wide.columns)
    if missing_groups:
        raise ValueError(f"Missing comparison groups: {sorted(missing_groups)}")
    wide = wide.reset_index()
    return paired_columns_summary(
        wide,
        run_col=run_col,
        a_col=group_a,
        b_col=group_b,
    )


def format_diff(value: float) -> str:
    """Format a signed percentage-point difference for LaTeX."""

    if round(value, 2) == 0:
        return "$0.00$"
    return f"${value:+.2f}$"


def format_p(value: float) -> str:
    """Format p-values consistently across all Chapter 8 tables."""

    return "$<0.001$" if value < 0.001 else f"${value:.3f}$"


def format_rate(value: float) -> str:
    return f"{value:.2f}"


def format_sem(value: float) -> str:
    return f"{value:.2f}"


def render_tabular(
    *,
    alignment: str,
    header_lines: Sequence[str],
    rows: Sequence[str],
) -> str:
    """Render a complete tabular block suitable for ``\\input``."""

    lines = [
        "% Generated by online-learning/scripts/generate_chapter8_tables.py.",
        "% Do not edit by hand; edit the generator or source Parquet instead.",
        f"\\begin{{tabular}}{{{alignment}}}",
        "    \\toprule",
        *[f"    {line}" for line in header_lines],
        "    \\midrule",
        *[f"    {row}" for row in rows],
        "    \\bottomrule",
        "\\end{tabular}",
        "",
    ]
    return "\n".join(lines)
