#!/usr/bin/env python3
"""Generate the seven supplementary discretized-covariate tables in Chapter 6.

OBSOLETE (2026-08-20): the "Supplementary Results with Discretized
Covariates" section this script fed has been removed from
06_heterogeneity_tradeoff.tex; see extract_chapter6_results.py for why.
Kept for provenance, not referenced by the chapter.

Usage, from the repository root::

    .venv/bin/python Meta-learning/scripts/generate_chapter6_tables.py
    .venv/bin/python Meta-learning/scripts/generate_chapter6_tables.py --check

The model-derived inputs are created by ``extract_chapter6_results.py``.  The
policy and delta-sensitivity tables are read directly from their analysis CSVs.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import pandas as pd


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[1]
CHAPTER6_RESULTS = REPO_ROOT / "Meta-learning" / "models" / "Chapter6"
POLICY_DIR = REPO_ROOT / "Meta-learning" / "models" / "Policy"
DELTA_DIR = REPO_ROOT / "Meta-learning" / "models" / "DeltaSensitivity"
OUTPUT_DIR = REPO_ROOT / "markdown_docs" / "thesis" / "generated_tables"
AUDIT_NAME = "chapter6_discretized_table_audit.csv"

ENDPOINTS = [
    ("bleed", "Bleeding"),
    ("barc_235", "Bleeding BARC 2/3/5"),
    ("mi", "MI"),
    ("death", "Cardiovascular death"),
    ("stroke", "Stroke"),
]


def _read(path: Path, required: set[str]) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Missing {path}. Run extract_chapter6_results.py first if this is a "
            "Chapter6 intermediate file."
        )
    data = pd.read_csv(path)
    missing = required - set(data.columns)
    if missing:
        raise ValueError(f"{path} is missing columns {sorted(missing)}")
    return data


def _render(alignment: str, headers: list[str], rows: list[str]) -> str:
    lines = [
        "% Generated by Meta-learning/scripts/generate_chapter6_tables.py.",
        "% Do not edit by hand; update the source results and rerun the generator.",
        f"\\begin{{tabular}}{{{alignment}}}",
        "    \\toprule",
        *[f"    {line}" for line in headers],
        "    \\midrule",
        *[f"    {line}" for line in rows],
        "    \\bottomrule",
        "\\end{tabular}",
        "",
    ]
    return "\n".join(lines)


def _signed(value: float, digits: int = 3) -> str:
    return f"${value:+.{digits}f}$"


def _unsigned(value: float, digits: int = 3) -> str:
    rendered = f"{value:.{digits}f}"
    if rendered.startswith("-0."):
        rendered = rendered[1:]
    return f"${rendered}$"


def _ci(lo: float, hi: float) -> str:
    return f"[{lo:+.3f},\,{hi:+.3f}]"


def _record(
    audit: list[dict[str, object]],
    *,
    table: str,
    row: str,
    metric: str,
    source: str,
    raw_value: object,
    display: str,
) -> None:
    audit.append(
        {
            "table": table,
            "row": row,
            "metric": metric,
            "source": source,
            "raw_value": raw_value,
            "display": display,
        }
    )


def _one(data: pd.DataFrame, **filters: str) -> pd.Series:
    subset = data
    for column, value in filters.items():
        subset = subset.loc[subset[column] == value]
    if len(subset) != 1:
        raise ValueError(f"Expected one row for {filters}, found {len(subset)}")
    return subset.iloc[0]


def build_estimator_tables(audit: list[dict[str, object]]) -> dict[str, str]:
    path = CHAPTER6_RESULTS / "chapter6_discretized_estimator_summary.csv"
    data = _read(
        path,
        {"endpoint", "estimator", "mean_cate", "sd_cate", "source", "source_detail"},
    )
    estimator_columns = [
        ("raw_ate", "Raw ATE"),
        ("t_learner", "T-learner"),
        ("causal_forest", "Causal for."),
        ("bcf", "BCF"),
        ("causalpfn", "CausalPFN"),
        ("interaction_forest", "Interact. for."),
    ]

    ate_rows: list[str] = []
    for endpoint, label in ENDPOINTS:
        cells: list[str] = []
        for estimator, _ in estimator_columns:
            result = _one(data, endpoint=endpoint, estimator=estimator)
            display = _signed(float(result["mean_cate"]))
            cells.append(display)
            _record(
                audit,
                table="ch6_ate_recovery",
                row=endpoint,
                metric=estimator,
                source=str(result["source"]),
                raw_value=float(result["mean_cate"]),
                display=display,
            )
        ate_rows.append(f"{label} & " + " & ".join(cells) + " \\\\")

    placebo_path = CHAPTER6_RESULTS / "chapter6_discretized_bcf_placebo_summary.csv"
    placebo = _read(placebo_path, {"endpoint", "sd_tau_placebo", "source"})
    dispersion_estimators = [
        ("t_learner", "T-learner"),
        ("causal_forest", "Causal for."),
        ("bcf", "BCF"),
        ("causalpfn", "CausalPFN"),
        ("interaction_forest", "Interact. for."),
    ]
    dispersion_rows: list[str] = []
    for endpoint, label in ENDPOINTS:
        cells = []
        for estimator, _ in dispersion_estimators:
            result = _one(data, endpoint=endpoint, estimator=estimator)
            display = f"{float(result['sd_cate']):.3f}"
            cells.append(display)
            _record(
                audit,
                table="ch6_cate_dispersion",
                row=endpoint,
                metric=estimator,
                source=str(result["source"]),
                raw_value=float(result["sd_cate"]),
                display=display,
            )
        if endpoint in {"bleed", "barc_235"}:
            floor = _one(placebo, endpoint=endpoint)
            floor_display = f"{float(floor['sd_tau_placebo']):.3f}"
            _record(
                audit,
                table="ch6_cate_dispersion",
                row=endpoint,
                metric="placebo_floor",
                source=str(floor["source"]),
                raw_value=float(floor["sd_tau_placebo"]),
                display=floor_display,
            )
        else:
            floor_display = "---"
        dispersion_rows.append(f"{label} & " + " & ".join(cells + [floor_display]) + " \\\\")

    return {
        "ch6_discretized_ate_recovery.tex": _render(
            "lrrrrrr",
            ["Endpoint & " + " & ".join(name for _, name in estimator_columns) + " \\\\"],
            ate_rows,
        ),
        "ch6_discretized_cate_dispersion.tex": _render(
            "lccccc|c",
            [
                "Endpoint & "
                + " & ".join(name for _, name in dispersion_estimators)
                + " & Placebo floor \\\\"
            ],
            dispersion_rows,
        ),
    }


def build_drtester(audit: list[dict[str, object]]) -> str:
    path = CHAPTER6_RESULTS / "chapter6_discretized_drtester_summary.csv"
    data = _read(path, {"endpoint", "estimator", "autoc", "p_value", "source"})
    estimators = ["causal_forest", "t_learner", "bcf"]
    rows: list[str] = []
    for endpoint, label in ENDPOINTS:
        cells: list[str] = []
        for estimator in estimators:
            result = _one(data, endpoint=endpoint, estimator=estimator)
            autoc = _signed(float(result["autoc"]))
            p_value = f"{float(result['p_value']):.2f}"
            cells.extend([autoc, p_value])
            _record(
                audit,
                table="ch6_drtester",
                row=endpoint,
                metric=f"{estimator}_autoc",
                source=str(result["source"]),
                raw_value=float(result["autoc"]),
                display=autoc,
            )
            _record(
                audit,
                table="ch6_drtester",
                row=endpoint,
                metric=f"{estimator}_p",
                source=str(result["source"]),
                raw_value=float(result["p_value"]),
                display=p_value,
            )
        rows.append(f"{label} & " + " & ".join(cells) + " \\\\")
    return _render(
        "lcccccc",
        [
            "& \\multicolumn{2}{c}{Causal forest} & \\multicolumn{2}{c}{T-learner} & \\multicolumn{2}{c}{BCF} \\\\ ",
            "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}",
            "Endpoint & AUTOC & $p$ & AUTOC & $p$ & AUTOC & $p$ \\\\ ",
        ],
        rows,
    )


def build_flexibility(audit: list[dict[str, object]]) -> str:
    path = CHAPTER6_RESULTS / "chapter6_discretized_flexibility_summary.csv"
    data = _read(path, {"endpoint", "level", "mean_cate", "sd_cate", "source"})
    levels = ["regularized", "medium", "flexible", "tuned"]
    rows: list[str] = []
    for endpoint, label in ENDPOINTS:
        cells: list[str] = []
        for level in levels:
            result = _one(data, endpoint=endpoint, level=level)
            mean_display = _unsigned(float(result["mean_cate"]))
            if float(result["mean_cate"]) < -0.0005:
                mean_display = f"${float(result['mean_cate']):.3f}$"
            sd_display = _unsigned(float(result["sd_cate"]))
            display = f"{mean_display} / {sd_display}"
            cells.append(display)
            _record(
                audit,
                table="ch6_flexibility",
                row=endpoint,
                metric=level,
                source=str(result["source"]),
                raw_value=f"mean={result['mean_cate']};sd={result['sd_cate']}",
                display=display,
            )
        rows.append(f"{label} & " + " & ".join(cells) + " \\\\")
    return _render(
        "lcccc",
        [
            "& \\multicolumn{4}{c}{mean CATE / std CATE} \\\\ ",
            "\\cmidrule(lr){2-5}",
            "Endpoint & Regularized & Medium & Flexible & Tuned (Optuna) \\\\ ",
        ],
        rows,
    )


def build_nace_ate(audit: list[dict[str, object]]) -> str:
    path = POLICY_DIR / "ate_per_endpoint.csv"
    data = _read(path, {"endpoint", "event_rate", "ATE_prolonged_minus_abbrev", "ci_lo", "ci_hi"})
    order = [
        ("NACE", "NACE"),
        ("bleed_barc235", "BARC 2/3/5 bleeding"),
        ("ischemia_macce", "MACCE"),
    ]
    rows: list[str] = []
    for endpoint, label in order:
        result = _one(data, endpoint=endpoint)
        rate = f"{float(result['event_rate']) * 100:.1f}\\%"
        ate = _signed(float(result["ATE_prolonged_minus_abbrev"]))
        ci = f"${_ci(float(result['ci_lo']), float(result['ci_hi']))}$"
        rows.append(f"{label} & {rate} & {ate} & {ci} \\\\")
        for metric, raw, display in (
            ("event_rate", result["event_rate"], rate),
            ("ate", result["ATE_prolonged_minus_abbrev"], ate),
            ("ci", f"{result['ci_lo']},{result['ci_hi']}", ci),
        ):
            _record(
                audit,
                table="ch6_nace_ate",
                row=endpoint,
                metric=metric,
                source=str(path.relative_to(REPO_ROOT)),
                raw_value=raw,
                display=display,
            )
    return _render(
        "lccc",
        ["Endpoint & Event rate & ATE & 95\\% CI \\\\"],
        rows,
    )


def build_policy_value(audit: list[dict[str, object]]) -> str:
    path = POLICY_DIR / "nace_policy_value.csv"
    data = _read(
        path,
        {"policy", "value", "pct_treated_prolonged", "impr_vs_best_fixed", "impr_lo", "impr_hi"},
    )
    order = [
        ("all_abbreviated", "All abbreviated"),
        ("all_prolonged", "All prolonged"),
        ("ate_sign", "ATE sign"),
        ("drpolicy_tree", "Policy tree"),
        ("drpolicy_forest", "Policy forest"),
    ]
    rows: list[str] = []
    for policy, label in order:
        result = _one(data, policy=policy)
        value = f"{float(result['value']):.3f}"
        pct = f"{float(result['pct_treated_prolonged']):.1f}"
        if policy == "all_abbreviated":
            improvement = "---"
        else:
            improvement = (
                f"{_signed(float(result['impr_vs_best_fixed']))} "
                f"${_ci(float(result['impr_lo']), float(result['impr_hi']))}$"
            )
        rows.append(f"{label} & {value} & {pct} & {improvement} \\\\")
        for metric, raw, display in (
            ("value", result["value"], value),
            ("pct_prolonged", result["pct_treated_prolonged"], pct),
            ("improvement", result["impr_vs_best_fixed"], improvement),
        ):
            _record(
                audit,
                table="ch6_policy_value",
                row=policy,
                metric=metric,
                source=str(path.relative_to(REPO_ROOT)),
                raw_value=raw,
                display=display,
            )
    return _render(
        "lccc",
        ["Policy & Value (NACE) & \\% prolonged & Improvement vs. best fixed [95\\% CI] \\\\"],
        rows,
    )


def build_delta_star(audit: list[dict[str, object]]) -> str:
    summary_path = DELTA_DIR / "delta_star_summary.csv"
    detect_path = DELTA_DIR / "detect_frac_by_delta.csv"
    summary = _read(summary_path, {"endpoint", "real_ATE", "delta_star_raw"})
    detect = _read(detect_path, {"endpoint", "delta", "scale", "detect_frac"})
    order = [
        ("bleed", "Bleeding"),
        ("barc_235", "Bleeding BARC 2/3/5"),
        ("mi", "MI"),
        ("death", "Cardiovascular death"),
        ("stroke", "Stroke"),
    ]
    rows: list[str] = []
    for endpoint, label in order:
        result = _one(summary, endpoint=endpoint)
        endpoint_detect = detect.loc[detect["endpoint"] == endpoint].sort_values("delta")
        if endpoint_detect.empty:
            raise ValueError(f"No sensitivity grid for {endpoint}")
        scale = str(endpoint_detect["scale"].iloc[0])
        delta = float(result["delta_star_raw"]) if pd.notna(result["delta_star_raw"]) else math.nan
        null_fraction = float(endpoint_detect.iloc[0]["detect_frac"])
        if math.isnan(delta):
            delta_display = "not reached"
            reading = f"null detection = {null_fraction * 100:.0f}\\%; unstable"
        elif scale == "risk_diff":
            delta_display = f"${delta:.3f}$ risk diff."
            ratio = delta / abs(float(result["real_ATE"]))
            reading = "more than twice the raw ATE" if ratio > 2 else "larger than the raw ATE"
        else:
            odds_ratio = math.exp(delta)
            delta_display = f"$\\mathrm{{OR}} = {odds_ratio:.2f}$"
            reading = "criterion already met at the null" if delta == 0 else "large effect modification"
        ate = _signed(float(result["real_ATE"]))
        rows.append(f"{label} & {ate} & {delta_display} & {reading} \\\\")
        _record(
            audit,
            table="ch6_delta_star",
            row=endpoint,
            metric="delta_star",
            source=str(summary_path.relative_to(REPO_ROOT)),
            raw_value=result["delta_star_raw"],
            display=delta_display,
        )
        _record(
            audit,
            table="ch6_delta_star",
            row=endpoint,
            metric="null_detection_fraction",
            source=str(detect_path.relative_to(REPO_ROOT)),
            raw_value=null_fraction,
            display=f"{null_fraction:.2f}",
        )
    return _render(
        "lrrl",
        ["Endpoint & Real ATE & $\\delta^*$ & Reading \\\\"],
        rows,
    )


def build_all() -> tuple[dict[str, str], str]:
    audit: list[dict[str, object]] = []
    outputs = build_estimator_tables(audit)
    outputs["ch6_discretized_drtester.tex"] = build_drtester(audit)
    outputs["ch6_discretized_flexibility.tex"] = build_flexibility(audit)
    outputs["ch6_discretized_nace_ate.tex"] = build_nace_ate(audit)
    outputs["ch6_discretized_policy_value.tex"] = build_policy_value(audit)
    outputs["ch6_discretized_delta_star.tex"] = build_delta_star(audit)
    audit_text = pd.DataFrame(audit).to_csv(index=False)
    return outputs, audit_text


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if any generated LaTeX fragment or the audit CSV is stale",
    )
    args = parser.parse_args()
    outputs, audit_text = build_all()
    expected = dict(outputs)
    expected[AUDIT_NAME] = audit_text
    if args.check:
        stale = [
            name
            for name, text in expected.items()
            if not (OUTPUT_DIR / name).exists()
            or (OUTPUT_DIR / name).read_text(encoding="utf-8") != text
        ]
        if stale:
            raise SystemExit("Stale Chapter 6 generated files: " + ", ".join(stale))
        print("All supplementary discretized Chapter 6 tables are current.")
        return

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, text in expected.items():
        (OUTPUT_DIR / name).write_text(text, encoding="utf-8")
        print(f"wrote {OUTPUT_DIR / name}")


if __name__ == "__main__":
    main()
